version: '3.8'

services:
  nextjs:
    container_name: nextjs_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
        - .:/app
        - /app/node_modules
        - /app/.next
    environment:
      - NODE_ENV=production
